### ISSUE TITLE
Allow manual initialization

### ISSUE THREAD

**Issue by hannesstruss** [hannesstruss/unearthed#7]
Currently, Unearthed initializes itself via a dummy `ContentProvider`. We should add a way to have users initialize the library manually.

**Comment by AlexKrupa** [comment]
Would making `Unearthed.init` public suffice? Then consumers could disable the `ContentProvider` in their `AndroidManifest.xml` and use the method to initialize manually (e.g. in `Application.onCreate`).

**Comment by hannesstruss** [comment]
That could work – though I'm actually inclined to just remove the ContentProvider magic and force manual initialization.

**Comment by AlexKrupa** [comment]
Sounds good too, thanks!

**Comment by hannesstruss** [comment]
@AlexKrupa just published 0.2.0 – should sync to Maven Central in a short while.
